# Generated by Django 4.2.7 on 2025-09-14 11:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Filament',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='نام فیلامنت')),
                ('color', models.CharField(max_length=100, verbose_name='رنگ')),
                ('material', models.CharField(choices=[('PLA', 'PLA - پلی لاکتیک اسید'), ('PLA+', 'PLA+ - پلی لاکتیک اسید بهبود یافته'), ('ABS', 'ABS - آکریلونیتریل بوتادین استایرن'), ('PETG', 'PETG - پلی اتیلن ترفتالات گلیکول'), ('TPU', 'TPU - ترموپلاستیک پولی یورتان'), ('WOOD', 'WOOD - چوبی'), ('METAL', 'METAL - فلزی'), ('CARBON', 'CARBON FIBER - کربن فایبر')], default='PLA+', max_length=20, verbose_name='نوع ماده')),
                ('initial_amount', models.FloatField(verbose_name='مقدار اولیه (متر)')),
                ('remaining_amount', models.FloatField(verbose_name='مقدار باقی\u200cمانده (متر)')),
                ('cost_per_kg', models.FloatField(default=1500000, verbose_name='قیمت (تومان/کیلو)')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
            ],
            options={
                'verbose_name': 'فیلامنت',
                'verbose_name_plural': 'فیلامنت\u200cها',
                'ordering': ['-created_date'],
            },
        ),
        migrations.CreateModel(
            name='PricingSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('singleton_id', models.PositiveSmallIntegerField(default=1, editable=False, unique=True)),
                ('power_price_per_kwh', models.DecimalField(decimal_places=2, default=3500, max_digits=12)),
                ('depreciation_per_hour', models.DecimalField(decimal_places=2, default=12000, max_digits=12)),
                ('filament_waste_percent', models.DecimalField(decimal_places=2, default=3, max_digits=6)),
                ('packaging_cost', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('post_processing_rate', models.DecimalField(decimal_places=2, default=25000, max_digits=12)),
                ('painting_rate_per_cm2', models.DecimalField(decimal_places=2, default=180, max_digits=12)),
                ('profit_percent', models.DecimalField(decimal_places=2, default=35, max_digits=6)),
                ('round_to_nearest', models.DecimalField(decimal_places=0, default=1000, max_digits=12)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(max_length=200, verbose_name='نام مدل')),
                ('code', models.PositiveIntegerField(unique=True, verbose_name='کد مدل')),
                ('picture', models.ImageField(blank=True, help_text='تصویر محصول  (اختیاری)', null=True, upload_to='project_images/', verbose_name='تصویر مدل')),
                ('filament_used_mm', models.FloatField(verbose_name='فیلامنت مصرفی (میلی\u200cمتر)')),
                ('print_time_hours', models.FloatField(verbose_name='زمان پرینت (ساعت)')),
                ('size_x', models.FloatField(verbose_name='ابعاد X (میلی\u200cمتر)')),
                ('size_y', models.FloatField(verbose_name='ابعاد Y (میلی\u200cمتر)')),
                ('size_z', models.FloatField(verbose_name='ابعاد Z (میلی\u200cمتر)')),
                ('filament_weight_used', models.FloatField(verbose_name='وزن فیلامنت (گرم)')),
                ('electricity_cost', models.FloatField(verbose_name='هزینه برق')),
                ('depreciation_cost', models.FloatField(verbose_name='هزینه استهلاک')),
                ('post_processing_enabled', models.BooleanField(default=False, verbose_name='پست\u200cپروسسینگ')),
                ('post_processing_cost', models.FloatField(default=0, verbose_name='هزینه پست\u200cپروسسینگ')),
                ('painting_enabled', models.BooleanField(default=False, verbose_name='رنگ\u200cآمیزی')),
                ('painting_cost', models.FloatField(default=0, verbose_name='هزینه رنگ\u200cآمیزی')),
                ('material_cost', models.FloatField(verbose_name='هزینه مواد')),
                ('total_cost', models.FloatField(verbose_name='هزینه کل')),
                ('selling_price', models.FloatField(verbose_name='قیمت فروش')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('filament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calculator.filament', verbose_name='فیلامنت')),
            ],
            options={
                'verbose_name': 'مدل',
                'verbose_name_plural': 'مدل\u200cها',
                'ordering': ['-created_date'],
            },
        ),
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_code', models.PositiveIntegerField(verbose_name='کد مدل')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='تعداد')),
                ('customer_name', models.CharField(blank=True, max_length=200, verbose_name='نام مشتری')),
                ('customer_phone', models.CharField(blank=True, max_length=20, verbose_name='شماره تماس')),
                ('unit_price', models.FloatField(verbose_name='قیمت واحد')),
                ('packaging_cost', models.FloatField(default=0, verbose_name='هزینه بسته\u200cبندی')),
                ('total_price', models.FloatField(verbose_name='قیمت کل')),
                ('sale_date', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ فروش')),
                ('notes', models.TextField(blank=True, verbose_name='یادداشت')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calculator.project', verbose_name='مدل')),
            ],
            options={
                'verbose_name': 'فروش',
                'verbose_name_plural': 'فروش\u200cها',
                'ordering': ['-sale_date'],
            },
        ),
    ]
